name: Deploy to GCP
on: push

jobs:
  deploy:
    runs-on: windows-latest
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      GCP_APP_NAME: ${{ secrets.GCP_APP_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ env.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Docker auth (potentially redundant)  # Check setup-buildx-action documentation
        run: gcloud auth configure-docker europe-west3-docker.pkg.dev  # Consider removing if redundant

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy Docker image (consider authentication for production)
        run: |
          gcloud run deploy ${{ env.GCP_APP_NAME }} \
            --image ${{ env.IMAGE_NAME }} \
            --region asia-southeast2 \
            --platform managed \
            --port=3838
          # Remove --allow-unauthenticated for production
